// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/history.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/works/[work].tsx";
import * as $6 from "./routes/works/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/history.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/works/[work].tsx": $5,
    "./routes/works/index.tsx": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
