name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install package
        run: npm install

      - name: Check lint & format
        run: npm run check

      - name: build
        run: npm run build
